apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cc-blp-react
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/KiranNT79/blp-app-argocd.git'
    targetRevision: HEAD
    path: frontend/cc-blp-react/integration/application/kubernetes/cc-blp-react/templates
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
