apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cc-blp-react
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/KiranNT79/blp-app-argocd
    targetRevision: HEAD
    path: ./cc-blp-react/integration/application/kubernetes/cc-blp-react
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: false
      selfHeal: false