{{- /*
(c) 2022 CARIAD SE, All rights reserved.

NOTICE:
All the information and materials contained herein, including the intellectual and technical concepts, are the property of CARIAD SE and may be covered by patents, patents in process, and are protected by trade secret and/or copyright law.
The copyright notice above does not evidence any actual or intended publication or disclosure of this source code, which includes information and materials that are confidential and/or proprietary and trade secrets of CARIAD SE.
Any reproduction, dissemination, modification, distribution, public performance, public display of or any other use of this source code and/or any other information and/or material contained herein without the prior written consent of CARIAD SE is strictly prohibited and in violation of applicable laws.
The receipt or possession of this source code and/or related information does not convey or imply any rights to reproduce, disclose or distribute its contents or to manufacture, use or sell anything that it may describe in whole or in part.
*/}}
{{- if (default false .Values.secrets.enabled) -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "frontend-gateway.fullname" . }}
spec:
  provider: azure
  secretObjects: # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
    - secretName: {{ include "frontend-gateway.fullname" . }}
      labels:
        spring.cloud.kubernetes.secret: "true"
      annotations:
        spring.cloud.kubernetes.secret.apps: {{ include "frontend-gateway.fullname" . }}-service
      type: Opaque
      data:
        {{- range $secret := .Values.secrets.objects }}
        - objectName: {{ $secret.alias }}
          key: {{ $secret.alias }}
        {{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: {{ .Values.secrets.userAssignedIdentityID | quote }}
    keyvaultName: {{ .Values.secrets.kvName | quote }}
    tenantId: {{ .Values.secrets.tenantId | quote }}
    objects: |
      array:
        {{- range $secret := .Values.secrets.objects }}
        - |
          objectName: {{ $secret.kvObjectName }}
          objectType: secret                     # object types: secret, key or cert
          objectAlias: {{ $secret.alias }}
        {{- end }}
{{- end }}
