apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cc-shell
  namespace: default
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/KiranNT79/blp-app-argocd.git'
    path: aspice/integration/application/kubernetes/cc-shell
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
