name: CD Pipeline

# on:
#   push:
#     paths:
#       - 'helm/cc-blp-react/**'
#       - '.github/workflows/cd.yml'
#       - 'argocd-application.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
          
    - name: Login to ArgoCD
      run: |
        argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
    
    - name: Apply ArgoCD Application
      run: |
        kubectl apply -f aspice/argocd-application.yaml
    
    - name: Sync ArgoCD Application
      run: |
        argocd app sync cc-shell

